# Site settings

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable : true

github: [metadata]
